package domain.entity

import kotlinx.serialization.Serializable

@Serializable
data class ComposedOutput(
    val loadoutName: String,
    val content: String,
    val fragmentCount: Int,
    val metadata: CompositionMetadata,
) {
    fun toFileContent(includeMetadata: Boolean = false): String =
        buildString {
            if (includeMetadata) {
                appendLine("<!-- Generated by Loadout CLI -->")
                appendLine("<!-- Loadout: $loadoutName -->")
                appendLine("<!-- Fragments: $fragmentCount -->")
                appendLine("<!-- Generated: ${metadata.generatedAt} -->")
                appendLine()
            }
            append(content)
        }
}
