package domain

import kotlinx.serialization.Serializable
import common.currentTimeMillis

@Serializable
data class ComposedOutput(
    val loadoutName: String,
    val content: String,
    val fragmentCount: Int,
    val metadata: CompositionMetadata
) {
    fun toFileContent(includeMetadata: Boolean = false): String = buildString {
        if (includeMetadata) {
            appendLine("<!-- Generated by Loadout CLI -->")
            appendLine("<!-- Loadout: $loadoutName -->")
            appendLine("<!-- Fragments: $fragmentCount -->")
            appendLine("<!-- Generated: ${metadata.generatedAt} -->")
            appendLine()
        }
        append(content)
    }
}

@Serializable
data class CompositionMetadata(
    val generatedAt: Long = currentTimeMillis(),
    val fragmentPaths: List<String> = emptyList(),
    val totalLines: Int = 0,
    val totalCharacters: Int = 0
) {
    companion object {
        fun from(content: String, fragmentPaths: List<String>): CompositionMetadata = 
            CompositionMetadata(
                fragmentPaths = fragmentPaths,
                totalLines = content.lines().size,
                totalCharacters = content.length
            )
    }
}