config:
  validation: true
  warningsAsErrors: true

ktlint:
  active: true
  # Common knobs to consider:
  # Filename:
  #   active: false
  # FunctionSignature:
  #   active: false
  # ImportOrdering:
  #   active: false
  # MaximumLineLength:
  #   active: false
  ChainMethodContinuation:
    active: false
  ClassSignature:
    active: false
  TrailingCommaOnCallSite:
    active: false
  BlankLineBetweenWhenConditions:
    active: false

complexity:
  active: true
  # Common knobs to consider:
  # LongMethod:
  #   active: false
  # NestedBlockDepth:
  #   active: false
  # TooManyFunctions:
  #   active: false

naming:
  active: true
  # Common knobs to consider:
  # PackageNaming:
  #   active: false
  # TopLevelPropertyNaming:
  #   active: false
  # MatchingDeclarationName:
  #   active: false

style:
  active: true
  # Common knobs to consider:
  # ForbiddenComment:
  #   active: false
  # MagicNumber:
  #   active: false
  # ReturnCount:
  #   active: false
  # ThrowsCount:
  #   active: false
  UnusedPrivateFunction:
    active: true
    allowedNames: ''
  UnusedPrivateProperty:
    active: true
    allowedNames: 'ignored|expected|serialVersionUID'
  UnusedVariable:
    active: true
    allowedNames: '_|ignored|expected'
